version: 2

executorType: docker

containerInfo:
  - image: node:6.9.2

stages:
  build:
    workDir: ~/express-pug-starter

    steps:
      - type: checkout

      - type: shell
        command: npm install

      - type: shell
        command: npm test
        environment:
          - NODE_ENV: "test"
